import type { Event } from "./types";

export const eventsData: Event[] = [
  {
    name: "SLS Miami 2025",
    location: "Miami, FL, USA",
    date: "2025-05-03",
    host: "Street League",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 36.8,
        country: "USA",
      },
      {
        skater_name: "Gustavo Ribeiro",
        placement: 2,
        score: 36.7,
        country: "POR",
      },
      {
        skater_name: "Felipe Gustavo",
        placement: 3,
        score: 36.5,
        country: "BRA",
      },
      { skater_name: "Shirai Sora", placement: 4, score: 27.7, country: "JPN" },
      {
        skater_name: "Giovanni Vianna",
        placement: 5,
        score: 27.2,
        country: "BRA",
      },
      {
        skater_name: "Netsuke Kairi",
        placement: 6,
        score: 18.2,
        country: "JPN",
      },
    ],
  },
  {
    name: "SLS Super Crown 2024",
    location: "São Paulo, Brazil",
    date: "2024-12-15",
    host: "Street League",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 36.8,
        country: "USA",
      },
      {
        skater_name: "Giovanni Vianna",
        placement: 2,
        score: 36.2,
        country: "BRA",
      },
    ],
  },
  {
    name: "X Games Chiba 2024 – Men's Skateboarding - Street",
    location: "Chiba, Japan",
    date: "2024-09-22",
    host: "X Games",
    results: [
      {
        skater_name: "Shirai Sora",
        placement: 1,
        score: 94.66,
        country: "JPN",
      },
      {
        skater_name: "Netsuke Kairi",
        placement: 2,
        score: 93.0,
        country: "JPN",
      },
      {
        skater_name: "Onodera Ginwoo",
        placement: 3,
        score: 89.0,
        country: "JPN",
      },
    ],
  },
  {
    name: "X Games Street Ventura 2024 – Men's Skateboarding - Street",
    location: "Ventura, CA, USA",
    date: "2024-07-21",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 95.0,
        country: "USA",
      },
      {
        skater_name: "Braden Hoban",
        placement: 2,
        score: 90.66,
        country: "USA",
      },
      {
        skater_name: "Gustavo Ribeiro",
        placement: 3,
        score: 87.0,
        country: "POR",
      },
    ],
  },
  {
    name: "SLS Super Crown 2023",
    location: "São Paulo, Brazil",
    date: "2023-12-3",
    host: "Street League",
    results: [
      {
        skater_name: "Giovanni Vianna",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Vincent Milou",
        placement: 2,
        score: 0,
        country: "FRA",
      },
      {
        skater_name: "Gustavo Ribiero",
        placement: 3,
        score: 0,
        country: "POR",
      },
    ],
  },
  {
    name: "SLS Super Crown 2021",
    location: "Jacksonville, FL, USA",
    date: "2021-11-14",
    host: "Street League",
    results: [
      {
        skater_name: "Jagger Eaton",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Lucas Rabelo",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Gustavo Ribiero",
        placement: 3,
        score: 0,
        country: "POR",
      },
    ],
  },
  {
    name: "SLS Unsanctioned 2020",
    location: "Southern California, USA",
    date: "2020-12-28",
    host: "Street League",
    results: [
      {
        skater_name: "Dashawn Jordan",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Jamie Foy",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Manny Santiago",
        placement: 3,
        score: 0,
        country: "PR",
      },
    ],
  },
  {
    name: "SLS Super Crown 2019",
    location: "São Paulo, Brazil",
    date: "2019-9-22",
    host: "Street League",
    results: [
      {
        skater_name: "Nyjah Juston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 2,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Gustavo Ribiero",
        placement: 3,
        score: 0,
        country: "POR",
      },
    ],
  },
  {
    name: "SLS Huntington Beach Finals 2018",
    location: "Huntington Beach, CA, USA",
    date: "2018-12-16",
    host: "Street League",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Deshawn Jordan",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Kevin Hoefler",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "SLS Super Crown 2017",
    location: "Los Angeles, CA, USA",
    date: "2017-9-15",
    host: "Street League",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Shane O'Neill",
        placement: 2,
        score: 0,
        country: "AUS",
      },
      {
        skater_name: "Kevin Hoefler",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "SLS Super Crown 2016",
    location: "Los Angeles, CA, USA",
    date: "2016-10-2",
    host: "Street League",
    results: [
      {
        skater_name: "Shane O' Neill",
        placement: 1,
        score: 0,
        country: "AUS",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Cody McEntire",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },

  {
    name: "SLS Super Crown 2015",
    location: "Chicago, Illinois, USA",
    date: "2015-10-04",
    host: "Street League",
    results: [
      {
        skater_name: "Kelvin Hoefler",
        placement: 1,
        score: "35.8",
        country: "BRA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: "35.7",
        country: "USA",
      },
      {
        skater_name: "Luan Oliveira",
        placement: 3,
        score: "34.1",
        country: "BRA",
      },
    ],
  },
  {
    name: "SLS Super Crown 2014",
    location: "Newark, New Jersey, USA",
    date: "2014-08-24",
    host: "Street League",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: "0",
        country: "USA",
      },
      {
        skater_name: "Torey Pudwill",
        placement: 2,
        score: "0",
        country: "USA",
      },
      {
        skater_name: "Ishod Wair",
        placement: 3,
        score: "0",
        country: "USA",
      },
    ],
  },
  {
    name: "SLS Super Crown 2013",
    location: "Newark, New Jersey, USA",
    date: "2013-08-25",
    host: "Street League",
    results: [
      {
        skater_name: "Chris Cole",
        placement: 1,
        score: "52.8",
        country: "USA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: "52.4",
        country: "USA",
      },
      {
        skater_name: "Luan Oliveira",
        placement: 3,
        score: "49.3",
        country: "BRA",
      },
    ],
  },

  {
    name: "X Games California 2023 – Men's Skateboarding - Street",
    location: "Ventura, CA, USA",
    date: "2023-07-23",
    host: "X Games",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 95.66,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 90.66,
        country: "BRA",
      },
      {
        skater_name: "Ryan Decenzo",
        placement: 3,
        score: 88.0,
        country: "CAN",
      },
    ],
  },
  {
    name: "X Games Summer 2022 – Men's Skateboarding - Street",
    location: "Ventura, CA, USA",
    date: "2022-07-20",
    host: "X Games",
    results: [
      {
        skater_name: "Shane O' Neill",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Vincent Milou",
        placement: 2,
        score: 0,
        country: "FRA",
      },
      {
        skater_name: "Ryan Decenzo",
        placement: 3,
        score: 0,
        country: "CAN",
      },
    ],
  },
  {
    name: "X Games Chiba 2022 – Men's Skateboarding - Street",
    location: "Chiba, Japan",
    date: "2022-04-22",
    host: "X Games",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Daiki Ikeda",
        placement: 2,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Sora Shirai",
        placement: 3,
        score: 0,
        country: "JPN",
      },
    ],
  },
  {
    name: "Tampa Pro 2024",
    location: "Tampa FL, USA ",
    date: "2024-04-7",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      { skater_name: "Jake Ilardi", placement: 3, score: 0, country: "USA" },
    ],
  },
  {
    name: "X Games Chiba 2023 – Men's Skateboarding - Street",
    location: "Chiba, Japan",
    date: "2023-05-14",
    host: "X Games",
    results: [
      {
        skater_name: "Onodera Ginwoo",
        placement: 1,
        score: 90.33,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 83.66,
        country: "BRA",
      },
      { skater_name: "Jamie Foy", placement: 3, score: 83.33, country: "USA" },
    ],
  },
  {
    name: "SLS Super Crown 2022",
    location: "Rio de Janeiro, Brazil",
    date: "2022-11-06",
    host: "Street League",
    results: [
      {
        skater_name: "Gustavo Ribeiro",
        placement: 1,
        score: 27.9,
        country: "POR",
      },
      {
        skater_name: "Braden Hoban",
        placement: 2,
        score: 27.7,
        country: "USA",
      },
      { skater_name: "Chris Jolin", placement: 3, score: 27.2, country: "USA" },
    ],
  },

  {
    name: "Olympics Tokyo 2020 – Men's Skateboarding - Street",
    location: "Tokyo, Japan",
    date: "2021-07-25",
    host: "Olympics",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Jagger Eaton",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },

  {
    name: "X Games Los Angeles 2010 – Men's Skateboarding - Street",
    location: "Los Angeles, USA",
    date: "2010-08-01",
    host: "X Games",
    results: [
      {
        skater_name: "Ryan Sheckler",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Paul Rodriguez",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "X Games Los Angeles 2011 – Men's Skateboarding - Street",
    location: "Los Angeles, USA",
    date: "2011-07-31",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Ryan Sheckler",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Chaz Ortiz",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "X Games Los Angeles 2012 – Men's Skateboarding - Street",
    location: "Los Angeles, USA",
    date: "2012-07-01",
    host: "X Games",
    results: [
      {
        skater_name: "Paul Rodriguez",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Ryan Sheckler",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "X Games Barcelona 2013 – Men's Skateboarding - Street",
    location: "Barcelona, Spain",
    date: "2013-05-18",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Paul Rodriguez",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Manny Santiago",
        placement: 3,
        score: 0,
        country: "PUR",
      },
    ],
  },
  {
    name: "X Games Austin 2014 – Men's Skateboarding - Street",
    location: "Austin, USA",
    date: "2014-06-08",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 95.0,
        country: "USA",
      },
      {
        skater_name: "Ishod Wair",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Chaz Ortiz",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "X Games Austin 2015 – Men's Skateboarding - Street",
    location: "Austin, USA",
    date: "2015-06-07",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 94.0,
        country: "USA",
      },
      {
        skater_name: "Luan Oliveira",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "X Games Austin 2016 – Men's Skateboarding - Street",
    location: "Austin, USA",
    date: "2016-06-04",
    host: "X Games",
    results: [
      {
        skater_name: "Ryan Decenzo",
        placement: 1,
        score: 87.33,
        country: "CAN",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: 87.0,
        country: "USA",
      },
      {
        skater_name: "Ishod Wair",
        placement: 3,
        score: 86.66,
        country: "USA",
      },
    ],
  },
  {
    name: "X Games Minneapolis 2017 – Men's Skateboarding - Street",
    location: "Minneapolis, USA",
    date: "2017-07-16",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Luan Oliveira",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "X Games Norway 2018 – Men's Skateboarding - Street",
    location: "Oslo, Norway",
    date: "2018-05-20",
    host: "X Games",
    results: [
      {
        skater_name: "Kelvin Hoefler",
        placement: 1,
        score: 94.33,
        country: "BRA",
      },
      {
        skater_name: "Jagger Eaton",
        placement: 2,
        score: 88.0,
        country: "USA",
      },
      {
        skater_name: "Felipe Gustavo",
        placement: 3,
        score: 83.66,
        country: "BRA",
      },
    ],
  },
  {
    name: "X Games Shanghai 2019 – Men's Skateboarding - Street",
    location: "Shanghai, China",
    date: "2019-06-02",
    host: "X Games",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 94.0,
        country: "USA",
      },
      {
        skater_name: "Dashawn Jordan",
        placement: 2,
        score: 91.66,
        country: "USA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 3,
        score: 90.0,
        country: "JPN",
      },
    ],
  },
  {
    name: "X Games Minneapolis 2019 – Men's Skateboarding - Street",
    location: "Minneapolis, USA",
    date: "2019-08-04",
    host: "X Games",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 89.0,
        country: "JPN",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: 88.0,
        country: "USA",
      },
      {
        skater_name: "Sora Shirai",
        placement: 3,
        score: 87.0,
        country: "JPN",
      },
    ],
  },
  {
    name: "X Games California 2021 – Men's Skateboarding - Street",
    location: "California, USA",
    date: "2021-07-23",
    host: "X Games",
    results: [
      {
        skater_name: "Shane O'Neill",
        placement: 1,
        score: 0,
        country: "AUS",
      },
      {
        skater_name: "Vincent Milou",
        placement: 2,
        score: 0,
        country: "FRA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 3,
        score: 0,
        country: "JPN",
      },
    ],
  },
  {
    name: "Tampa Pro 2024",
    location: "Tampa, Florida, USA",
    date: "2024-04-07",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Jake Ilardi",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2023",
    location: "Tampa, Florida, USA",
    date: "2023-03-05",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Yuto Horigome",
        placement: 1,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Jake Ilardi",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2022",
    location: "Tampa, Florida, USA",
    date: "2022-05-06",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Jamie Foy",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Vincent Milou",
        placement: 2,
        score: 0,
        country: "FRA",
      },
      {
        skater_name: "Jake Ilardi",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2021",
    location: "Tampa, Florida, USA",
    date: "2021-04-25",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Shane O'Neill",
        placement: 1,
        score: 0,
        country: "AUS",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 2,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "Tampa Pro 2020",
    location: "Tampa, Florida, USA",
    date: "2020-03-01",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 2,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "Tampa Pro 2019",
    location: "Tampa, Florida, USA",
    date: "2019-03-03",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Carlos Ribeiro",
        placement: 1,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 2,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Jamie Foy",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2018",
    location: "Tampa, Florida, USA",
    date: "2018-03-04",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Jagger Eaton",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 2,
        score: 0,
        country: "JPN",
      },
      {
        skater_name: "Carlos Ribeiro",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "Tampa Pro 2017",
    location: "Tampa, Florida, USA",
    date: "2017-03-05",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Louie Lopez",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Carlos Ribeiro",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Yuto Horigome",
        placement: 3,
        score: 0,
        country: "JPN",
      },
    ],
  },
  {
    name: "Tampa Pro 2016",
    location: "Tampa, Florida, USA",
    date: "2016-03-06",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Shane O'Neill",
        placement: 1,
        score: 0,
        country: "AUS",
      },
      {
        skater_name: "Luan Oliveira",
        placement: 2,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2015",
    location: "Tampa, Florida, USA",
    date: "2015-03-22",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Luan Oliveira",
        placement: 1,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Kelvin Hoefler",
        placement: 3,
        score: 0,
        country: "BRA",
      },
    ],
  },
  {
    name: "Tampa Pro 2014",
    location: "Tampa, Florida, USA",
    date: "2014-03-23",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Nyjah Huston",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Chaz Ortiz",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Alec Majerus",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2013",
    location: "Tampa, Florida, USA",
    date: "2013-03-24",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Luan Oliveira",
        placement: 1,
        score: 0,
        country: "BRA",
      },
      {
        skater_name: "Nyjah Huston",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Chaz Ortiz",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2012",
    location: "Tampa, Florida, USA",
    date: "2012-03-25",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Torey Pudwill",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Chaz Ortiz",
        placement: 2,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Sean Malto",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
  {
    name: "Tampa Pro 2011",
    location: "Tampa, Florida, USA",
    date: "2011-03-13",
    host: "Skatepark of Tampa",
    results: [
      {
        skater_name: "Dennis Busenitz",
        placement: 1,
        score: 0,
        country: "USA",
      },
      {
        skater_name: "Shane O'Neill",
        placement: 2,
        score: 0,
        country: "AUS",
      },
      {
        skater_name: "Eric Koston",
        placement: 3,
        score: 0,
        country: "USA",
      },
    ],
  },
];
